settings:
  root_dir: "./datasets/facemask_segmetation/images"
  train_anns: "./datasets/facemask_segmetation/annotations/train.csv"
  val_anns: "./datasets/facemask_segmetation/annotations/val.csv"

  checkpoint_path: 'weights' #"/content/drive/MyDrive/weights/Places365 Inpainting/unet/phase 1"
  sample_folder: 'sample' #"/content/drive/MyDrive/results/Places365 Inpainting/unet/phase 1"

  cuda: True
  lr: 0.001
  batch_size: 4
  num_workers: 4

  step_iters: [50000, 75000, 100000]
  gamma: 0.1
  
  visualize_per_iter: 1000
  save_per_iter: 1000
  print_per_iter: 10
  num_epochs: 100

  img_size: 512

